### ISSUE TITLE
[nuxt] Cannot find module 'ignore'

### ISSUE THREAD

**Issue by INeedJobToStartWork** [antfu/eslint-flat-config-viewer#14] opened 2024-01-02 22:53 UTC
### Describe the bug

I want to use `npx eslint-flat-config-viewer` but it output error 

Logs:

PS D:\INEEDJ\FluidUI> npx eslint-flat-config-viewer
Listening on http://127.0.0.1:7777
[nuxt] [request error] [unhandled] [500] Cannot find module 'ignore'
Require stack:
- C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
- C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\eslint\lib\cli-engine\file-enumerator.js
- C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\eslint\lib\unsupported-api.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
  at Module._load (node:internal/modules/cjs/loader:985:27)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
  at require (node:internal/modules/helpers:176:18)
  at Object.<anonymous> (C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:12:14)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
  at Module.load (node:internal/modules/cjs/loader:1207:32)
  at Module._load (node:internal/modules/cjs/loader:1023:12)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
[nuxt] [request error] [unhandled] [500] Cannot find module 'ignore'
Require stack:
- C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
- C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\eslint\lib\cli-engine\file-enumerator.js
- C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\eslint\lib\unsupported-api.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
  at Module._load (node:internal/modules/cjs/loader:985:27)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
  at require (node:internal/modules/helpers:176:18)
  at Object.<anonymous> (C:\Users\gigaz\AppData\Local\npm-cache\_npx\83a9f1808c65f925\node_modules\eslint-flat-config-viewer\dist\server\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:12:14)
  at Module._compile (node:internal/modules/cjs/loader:1376:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
  at Module.load (node:internal/modules/cjs/loader:1207:32)
  at Module._load (node:internal/modules/cjs/loader:1023:12)
  at Module.require (node:internal/modules/cjs/loader:1235:19)
Terminate batch job (Y/N)? y

### Reproduction

https://github.com/INeedJobToStartWork/FluidUI/tree/main

### System Info

```Shell
System:
    OS: Windows 11 10.0.22000
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    Memory: 20.37 GB / 31.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Managers:
    Cargo: 1.73.0 - ~\.cargo\bin\cargo.EXE
  Utilities:
    Git: 2.40.0.
    Curl: 8.0.1 - C:\WINDOWS\system32\curl.EXE
  IDEs:
    VSCode: 0.21.4 - c:\Users\gigaz\AppData\Local\Programs\cursor-nightly\resources\app\bin\code.CMD
    Visual Studio: 17.7.34202.233 (Visual Studio Community 2022)
  Languages:
    Rust: 1.73.0
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-01-03 01:10
The reproduction is not minimal, can't help with that.

**Comment by antfu** [comment] 2024-01-03 01:11
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2024-01-03 01:11 UTC

**Comment by subframe7536** [comment] 2024-01-03 10:10
same here, use https://github.com/antfu/eslint-config repo and run 
```shell
npx eslint-flat-config-viewer@latest
```

everything well in `v0.1.3`

**Comment by emavitta** [comment] 2024-01-03 10:24
Same problem, same fix working.

**Comment by INeedJobToStartWork** [comment] 2024-01-03 10:32
> same here, use https://github.com/antfu/eslint-config repo and run
> 
> ```shell
> npx eslint-flat-config-viewer@latest
> ```
> 
> everything well in `v0.1.3`


I did clone this repo, installed dependencies and run this command - still have this error.
I have error on all configs.

Nuxt giving same error, white website - i dont have even error with this default config (on website tip).
I have this problem from last update i think.

(I added .env with `ESLINT_USE_FLAT_CONFIG=true` too)

```
  System:
    OS: Windows 11 10.0.22000
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    Memory: 21.14 GB / 31.92 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22000.120
```

![image](https://github.com/antfu/eslint-flat-config-viewer/assets/97305201/fa280467-5aec-465c-9f5e-d0e2df447b74)

Idk it gonna help in something but its error on browser
